"""scriptgen.templates — turn a parameter dict into a training script.

Three modes, because "generate a script" means three different things
depending on what you already have:

* :func:`generate` writes a complete, runnable script from scratch.
* :func:`inject` puts a config block into an *existing* script, replacing
  the previous one if it finds it. This is the one people actually use
  after the first day — they have a training loop they like and want the
  GUI to drive its constants.
* :func:`as_config` emits just the values, as JSON or as a Python dict,
  for a loop that reads its own config.

The generated script is deliberately readable
---------------------------------------------
It is not a wrapper that calls a HyperNix function with 40 keyword
arguments. It is a training loop someone can read, edit, and stop using
this GUI for. A generator whose output can only be regenerated is a
generator people abandon as soon as they need one thing it does not do.

Values are emitted through :func:`_literal`, never interpolated as text.
A dataset path with a quote in it is not an attack here — the person
typing it is the person running it — but it is a syntax error, and a
generator that produces one is broken.
"""
from __future__ import annotations

import json
import re
import textwrap
import time
from typing import Any

from .params import ALL_PARAMS, GROUPS

__all__ = ["generate", "inject", "as_config", "BEGIN_MARKER", "END_MARKER"]

#: Injection markers. Distinctive enough not to collide with real code
#: and stable across versions — changing them would orphan every script
#: someone has already injected into.
BEGIN_MARKER = "# --- hypernix scriptgen: begin ---"
END_MARKER = "# --- hypernix scriptgen: end ---"

_BLOCK_RE = re.compile(
    re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
    re.DOTALL,
)


def _literal(value: Any) -> str:
    """Render a Python literal. Never string interpolation."""
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int,)):
        return repr(value)
    if isinstance(value, float):
        # repr(), not a format spec. Python's float repr is the shortest
        # string that round-trips exactly, so 3e-05 stays "3e-05" rather
        # than becoming "3.000000e-05" — and a formatted literal can
        # silently lose precision, which for a learning rate is a
        # different run than the one the GUI showed.
        return repr(value)
    if isinstance(value, (list, tuple)):
        return "(" + ", ".join(_literal(v) for v in value) + ")"
    return repr(value)


def _config_block(values: dict[str, Any], *, include_comments: bool = True) -> str:
    """The CONFIG dict, grouped and commented like the form."""
    lines = [BEGIN_MARKER, "CONFIG = {"]
    for group in GROUPS:
        emitted = [p for p in group.params if p.name in values]
        if not emitted:
            continue
        if include_comments:
            lines.append(f"    # --- {group.title} ---")
        for param in emitted:
            value = values[param.name]
            rendered = f"    {param.script_name!r}: {_literal(value)},"
            if include_comments and param.hint:
                # Hints wrap rather than run off the edge; a generated
                # file with 200-character lines is a file people reformat
                # before reading, and then the markers move.
                for hint_line in textwrap.wrap(param.hint, width=76):
                    lines.append(f"    # {hint_line}")
            lines.append(rendered)
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append(END_MARKER)
    return "\n".join(lines)


def as_config(values: dict[str, Any], *, fmt: str = "python") -> str:
    """Just the values: ``"python"``, ``"json"`` or ``"env"``."""
    payload = {
        ALL_PARAMS[name].script_name: value
        for name, value in values.items()
        if name in ALL_PARAMS
    }
    if fmt == "json":
        return json.dumps(payload, indent=2, default=str)
    if fmt == "env":
        lines = []
        for key, value in payload.items():
            rendered = (
                str(int(value)) if isinstance(value, bool) else str(value)
            )
            lines.append(f"HYPERNIX_{key.upper()}={rendered}")
        return "\n".join(lines)
    if fmt == "python":
        return _config_block(values)
    raise ValueError(f"fmt must be python, json or env; got {fmt!r}")


def generate(values: dict[str, Any], *, include_comments: bool = True) -> str:
    """A complete training script."""
    notes = str(values.get("notes") or "").strip()
    header = [
        '"""Training script generated by `hnx scriptgen`.',
        "",
        f"Generated {time.strftime('%Y-%m-%d %H:%M:%S')}.",
    ]
    if notes:
        header.extend(["", *textwrap.wrap(notes, width=76)])
    header.extend(
        [
            "",
            "This is an ordinary training loop, not a wrapper. Edit it. The block",
            "between the scriptgen markers is the only part the GUI rewrites, so",
            "anything you change outside it survives a regeneration.",
            '"""',
        ]
    )

    body = f'''
from __future__ import annotations

import json
import logging
import math
import os
import sys
import time
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("train")

{_config_block(values, include_comments=include_comments)}


def build_optimizer(model, config):
    """Build the optimiser named in CONFIG.

    The Pressure Cooker family lives in hypernix.optimizers; everything
    else comes from torch. The 6-bit momentum mode is passed only to the
    optimisers that have a momentum buffer to pack — see
    hypernix.quant.formats.SIX_BIT_MODES.
    """
    import torch

    name = config["optimizer"]
    params = [p for p in model.parameters() if p.requires_grad]
    common = dict(
        lr=config["learning_rate"],
        weight_decay=config["weight_decay"],
    )

    if name.lower().startswith(("pressurecooker", "agedcooker", "ultraagedcooker")):
        from hypernix import optimizers as hnx_optim

        cls = getattr(hnx_optim, name, None)
        if cls is None:
            raise SystemExit(
                f"{{name}} is not available in this hypernix build. "
                f"Available: {{[n for n in dir(hnx_optim) if 'ooker' in n]}}"
            )
        extra = {{}}
        if config.get("six_bit_mode", "off") != "off":
            extra["six_bit_mode"] = config["six_bit_mode"]
        return cls(params, betas=(config["beta1"], config["beta2"]),
                   eps=config["eps"], **common, **extra)

    if name == "AdamW":
        return torch.optim.AdamW(
            params, betas=(config["beta1"], config["beta2"]), eps=config["eps"], **common
        )
    if name == "SGD":
        return torch.optim.SGD(params, momentum=config["beta1"], **common)
    if name == "Adafactor":
        from torch.optim import Adafactor  # torch >= 2.5

        return Adafactor(params, **common)
    if name == "Lion":
        try:
            from lion_pytorch import Lion
        except ImportError:
            raise SystemExit("Lion needs `pip install lion-pytorch`") from None
        return Lion(params, betas=(config["beta1"], config["beta2"]), **common)
    raise SystemExit(f"Unknown optimizer {{name!r}}")


def build_scheduler(optimizer, config, total_steps):
    """Warmup then decay, per CONFIG['lr_scheduler'].

    warmup_steps overrides warmup_ratio when non-zero, which is what a
    resumed run needs — the ratio is relative to a total the resumed run
    no longer has.
    """
    import torch

    warmup = config["warmup_steps"] or int(total_steps * config["warmup_ratio"])
    floor = config["min_lr_ratio"]
    kind = config["lr_scheduler"]

    def factor(step: int) -> float:
        if warmup and step < warmup:
            return step / max(1, warmup)
        progress = (step - warmup) / max(1, total_steps - warmup)
        progress = min(1.0, max(0.0, progress))
        if kind == "linear":
            return max(floor, 1.0 - progress)
        if kind == "constant_with_warmup":
            return 1.0
        if kind == "polynomial":
            return max(floor, (1.0 - progress) ** 2)
        if kind == "wsd":
            # Hold, then decay only over the last 20%: a run stopped
            # early is still at a usable learning rate.
            return 1.0 if progress < 0.8 else max(floor, 1.0 - (progress - 0.8) / 0.2)
        if kind == "cosine_with_restarts":
            cycle = (progress * 4) % 1.0
            return max(floor, 0.5 * (1.0 + math.cos(math.pi * cycle)))
        return max(floor, 0.5 * (1.0 + math.cos(math.pi * progress)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, factor)


def compute_loss(logits, labels, config):
    """CONFIG['loss_function'], applied to next-token prediction."""
    import torch
    import torch.nn.functional as F

    kind = config["loss_function"]
    shift_logits = logits[..., :-1, :].contiguous()
    shift_labels = labels[..., 1:].contiguous()
    flat_logits = shift_logits.view(-1, shift_logits.size(-1))
    flat_labels = shift_labels.view(-1)

    if kind == "cross_entropy":
        return F.cross_entropy(flat_logits, flat_labels, ignore_index=-100)
    if kind == "label_smoothed_ce":
        return F.cross_entropy(
            flat_logits, flat_labels, ignore_index=-100,
            label_smoothing=config["label_smoothing"],
        )
    if kind == "z_loss_ce":
        # Cross-entropy plus a penalty on logit magnitude. Cheap, and it
        # keeps long runs from drifting into numerically awkward logits.
        ce = F.cross_entropy(flat_logits, flat_labels, ignore_index=-100)
        z = torch.logsumexp(flat_logits, dim=-1).pow(2).mean()
        return ce + 1e-4 * z
    if kind == "focal":
        ce = F.cross_entropy(flat_logits, flat_labels, ignore_index=-100, reduction="none")
        return ((1 - torch.exp(-ce)) ** 2 * ce).mean()
    if kind == "mse":
        return F.mse_loss(flat_logits, F.one_hot(
            flat_labels.clamp(min=0), flat_logits.size(-1)).float())
    raise SystemExit(f"Unknown loss {{kind!r}}")


def apply_hardware_tuning(config):
    """Let the Pascal tuner override dtype and batching on sm_61.

    Only when CONFIG asks for it. The tuner knows one thing this script
    cannot: that FP16 arithmetic is 1:64 on a GTX 1080 and 2:1 on a
    P100, so "use fp16" means opposite things on two cards that both
    report compute capability 6.x.
    """
    if not config.get("pascal_autotune"):
        return config

    try:
        from hypernix.system.pascal import autotune, detect
    except ImportError:
        log.warning("pascal auto-tune requested but hypernix.system.pascal is unavailable")
        return config

    info = detect()
    if not info.is_pascal:
        log.info("no Pascal GPU detected; leaving CONFIG as written")
        return config

    tuning = autotune(info, sequence_length=config["sequence_length"])
    log.info("Pascal detected (%s); applying tuned settings", info.name)
    for key, value in (
        ("precision", "fp16_fp32_compute" if tuning.compute_dtype == "fp32" else "fp16"),
        ("micro_batch", tuning.micro_batch),
        ("gradient_accumulation", tuning.gradient_accumulation),
        ("gradient_checkpointing", tuning.gradient_checkpointing),
    ):
        if config.get(key) != value:
            log.info("  %s: %r -> %r", key, config.get(key), value)
            config[key] = value
    for warning in tuning.warnings:
        log.warning("  %s", warning)
    return config


def main() -> int:
    import torch

    config = dict(CONFIG)
    config = apply_hardware_tuning(config)

    torch.manual_seed(config["seed"])
    output = Path(config["output_dir"])
    output.mkdir(parents=True, exist_ok=True)
    (output / "config.json").write_text(json.dumps(config, indent=2, default=str))

    effective_batch = config["micro_batch"] * config["gradient_accumulation"]
    log.info("effective batch %d (%d x %d)", effective_batch,
             config["micro_batch"], config["gradient_accumulation"])

    # ------------------------------------------------------------------
    # Replace this section with your own model and data loading. Nothing
    # below the marker block is regenerated, so edits here survive.
    # ------------------------------------------------------------------
    raise SystemExit(
        "This generated script has no model or dataset loader yet.\\n"
        "Fill in main() with your own loading code — build_optimizer, "
        "build_scheduler and compute_loss above are ready to use."
    )


if __name__ == "__main__":
    sys.exit(main())
'''
    return "\n".join(header) + body


def inject(existing: str, values: dict[str, Any], *, include_comments: bool = True) -> str:
    """Put the config block into an existing script.

    Replaces a previous block when the markers are present, so
    regenerating does not stack copies. When they are not, the block goes
    after the imports rather than at the top — a CONFIG dict above the
    imports is legal and reads as though someone pasted it in a hurry.
    """
    block = _config_block(values, include_comments=include_comments)
    if _BLOCK_RE.search(existing):
        return _BLOCK_RE.sub(lambda _: block, existing, count=1)

    lines = existing.splitlines()
    insert_at = 0
    in_docstring = False
    quote = ""
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not in_docstring and stripped[:3] in ('"""', "'''"):
            quote = stripped[:3]
            # A single-line docstring opens and closes on the same line.
            if not (len(stripped) > 3 and stripped.endswith(quote)):
                in_docstring = True
            insert_at = index + 1
            continue
        if in_docstring:
            if quote in stripped:
                in_docstring = False
            insert_at = index + 1
            continue
        if stripped.startswith(("import ", "from ")) or not stripped:
            insert_at = index + 1
        elif stripped.startswith("#"):
            continue
        else:
            break

    return "\n".join([*lines[:insert_at], "", block, "", *lines[insert_at:]]) + "\n"
